// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("2.0.19")>]
[<assembly: AssemblyFileVersionAttribute("2.0.19")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "2.0.19"
    let [<Literal>] AssemblyFileVersion = "2.0.19"
